---
  # ---------------------------
  # Storm
  # ---------------------------

  - name: Storm | Ensure group "storm" exists
   group: name=storm state=present

  - name: Storm | Ensure user "storm" exists
   user: name=storm group=storm

  - name: Storm | Ensure {{storm_build}} zip is present
  get_url:
    url: "{{storm_mirror}}/{{storm_version}}/{{storm_build}}.zip"
    dest: "/tmp/{{storm_build}}.zip"
    owner: storm
    group: storm

  - name: Storm | Ensure zip is extracted
    unarchive: src=/tmp/{{storm_build}}.zip dest=/home/storm copy=no creates=/home/storm/{{storm_build}}

  - name: Storm | Ensure "current" symlink is present
    file: src=/home/storm/{{storm_build}} dest=/home/storm/current owner=storm group=storm state=link

  - name: Storm | Ensure data directory exists
    file: path={{storm_data_dir}} state=directory mode=0755 owner=storm group=storm

  - name: Storm | Ensure config is present
    template: src=files/kafka/server.properties dest=/home/kafka/current/config/server.properties mode=0644 owner=kafka group=kafka
